# MiniWorld Theme Hub - Apply Engine
# Shared by bootstrap.ps1 and can be called standalone.

param(
  [string]$HubRoot = 'D:\cursor-themes\miniworld-system',
  [string]$Scheme,
  [string]$Background,
  [string]$ButtonSkin,
  [string]$EnergySword = '',
  [switch]$WriteSettings = $true
)

$ErrorActionPreference = 'Stop'

function Get-State {
  $statePath = Join-Path $HubRoot 'state.json'
  return (Get-Content $statePath -Raw -Encoding UTF8 | ConvertFrom-Json)
}

function Save-State($state) {
  $state | ConvertTo-Json -Depth 8 | Set-Content (Join-Path $HubRoot 'state.json') -Encoding UTF8
}

function Get-Scheme($id) {
  $path = Join-Path $HubRoot "schemes\$id\scheme.json"
  if (-not (Test-Path $path)) { throw "Scheme not found: $id" }
  return (Get-Content $path -Raw -Encoding UTF8 | ConvertFrom-Json)
}

function Write-ActiveThemeCss($schemeId, $buttonSkin, $energySword) {
  # IMPORTANT: Custom CSS Loader inlines this file into workbench.html.
  # @import of file:// URLs is blocked by CSP — concatenate instead.
  $activeDir = Join-Path $HubRoot 'css\active'
  New-Item -ItemType Directory -Force -Path $activeDir | Out-Null
  $parts = @(
    (Join-Path $HubRoot 'css\textures.css'),
    (Join-Path $HubRoot 'css\icons.css'),
    (Join-Path $HubRoot 'css\base.css'),
    (Join-Path $HubRoot 'css\windows.css'),
    (Join-Path $HubRoot 'css\chat.css'),
    (Join-Path $HubRoot "css\buttons\$buttonSkin.css")
  )
  if ($energySword) {
    $parts += (Join-Path $HubRoot 'css\cursor.css')
  }
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine("/* AUTO-GENERATED by MiniWorld Theme Hub — do not edit by hand */")
  [void]$sb.AppendLine("/* scheme: $schemeId | button: $buttonSkin | sword: $energySword */")
  [void]$sb.AppendLine('')
  foreach ($p in $parts) {
    if (-not (Test-Path $p)) { throw "CSS missing: $p" }
    [void]$sb.AppendLine("/* ---- $(Split-Path $p -Leaf) ---- */")
    [void]$sb.AppendLine([System.IO.File]::ReadAllText($p))
    [void]$sb.AppendLine('')
  }
  $outPath = Join-Path $activeDir 'theme.css'
  [System.IO.File]::WriteAllText($outPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
}

function Build-BackgroundConfig($scheme, $bgFile) {
  $bgPath = Join-Path $HubRoot "assets\backgrounds\$bgFile"
  if (-not (Test-Path $bgPath)) { throw "Background not found: $bgFile" }
  $norm = ($bgPath -replace '\\', '/')
  $op = $scheme.backgroundOpacity
  return @{
    editor = @{
      useFront = $false
      images = @($norm)
      style = @{
        'background-size' = 'cover'
        'background-position' = 'center'
        'background-repeat' = 'no-repeat'
        opacity = [string]$op.editor
      }
    }
    auxiliarybar = @{
      useFront = $false
      images = @($norm)
      style = @{
        'background-size' = 'cover'
        'background-position' = 'center'
        'background-repeat' = 'no-repeat'
        opacity = [string]$op.auxiliarybar
      }
    }
    sidebar = @{
      useFront = $false
      images = @($norm)
      style = @{
        'background-size' = 'cover'
        'background-position' = 'center'
        'background-repeat' = 'no-repeat'
        opacity = [string]$op.sidebar
      }
    }
    panel = @{
      useFront = $false
      images = @($norm)
      style = @{
        'background-size' = 'cover'
        'background-position' = 'center'
        'background-repeat' = 'no-repeat'
        opacity = [string]$op.panel
      }
    }
  }
}

function ConvertTo-Hashtable($obj) {
  $ht = @{}
  if ($null -eq $obj) { return $ht }
  foreach ($p in $obj.PSObject.Properties) {
    $ht[$p.Name] = $p.Value
  }
  return $ht
}

function Merge-UserSettings($scheme, $bgCfg, $themeCssUri) {
  $settingsPath = Join-Path $env:APPDATA 'Cursor\User\settings.json'
  if (-not (Test-Path $settingsPath)) { throw "settings.json not found: $settingsPath" }

  $raw = Get-Content $settingsPath -Raw -Encoding UTF8
  # Strip // comments for parse (keep simple: only full-line comments)
  $jsonText = ($raw -split "`n" | ForEach-Object {
    if ($_ -match '^\s*//') { '' } else { $_ }
  }) -join "`n"

  $settings = $jsonText | ConvertFrom-Json

  $colors = ConvertTo-Hashtable $scheme.colors
  $tokens = ConvertTo-Hashtable $scheme.tokenColors

  $settings | Add-Member -NotePropertyName 'workbench.colorTheme' -NotePropertyValue $scheme.colorTheme -Force
  $settings | Add-Member -NotePropertyName 'workbench.colorCustomizations' -NotePropertyValue $colors -Force
  $settings | Add-Member -NotePropertyName 'editor.tokenColorCustomizations' -NotePropertyValue @{
    comments = $tokens.comments
    strings = $tokens.strings
    keywords = $tokens.keywords
    functions = $tokens.functions
    variables = $tokens.variables
    numbers = $tokens.numbers
    types = $tokens.types
  } -Force

  $settings | Add-Member -NotePropertyName 'background.enabled' -NotePropertyValue $true -Force
  $settings | Add-Member -NotePropertyName 'background.editor' -NotePropertyValue $bgCfg.editor -Force
  $settings | Add-Member -NotePropertyName 'background.auxiliarybar' -NotePropertyValue $bgCfg.auxiliarybar -Force
  $settings | Add-Member -NotePropertyName 'background.sidebar' -NotePropertyValue $bgCfg.sidebar -Force
  $settings | Add-Member -NotePropertyName 'background.panel' -NotePropertyValue $bgCfg.panel -Force

  $settings | Add-Member -NotePropertyName 'vscode_custom_css.imports' -NotePropertyValue @($themeCssUri) -Force
  $settings | Add-Member -NotePropertyName 'vscode_custom_css.policy' -NotePropertyValue $true -Force

  # Marker for restore / tooling
  $settings | Add-Member -NotePropertyName 'miniworldThemeHub.enabled' -NotePropertyValue $true -Force
  $settings | Add-Member -NotePropertyName 'miniworldThemeHub.hubRoot' -NotePropertyValue ($HubRoot -replace '\\','/') -Force

  $out = $settings | ConvertTo-Json -Depth 30
  # Prefer UTF8 no BOM for VS Code
  [System.IO.File]::WriteAllText($settingsPath, $out, (New-Object System.Text.UTF8Encoding $false))
}

# --- main ---
$state = Get-State
if ($Scheme) { $state.scheme = $Scheme }
if ($Background) { $state.background = $Background }
if ($ButtonSkin) { $state.buttonSkin = $ButtonSkin }
if ($EnergySword -ne '') {
  $state.energySword = $EnergySword -in @('1', 'true', 'True', 'TRUE', '$true', 'yes', 'on')
}
if ($null -eq $state.PSObject.Properties['energySword'] -or $null -eq $state.energySword) {
  $state | Add-Member -NotePropertyName 'energySword' -NotePropertyValue $true -Force
}
$state | Add-Member -NotePropertyName 'enabled' -NotePropertyValue $true -Force

$schemeObj = Get-Scheme $state.scheme
if (-not $state.background) { $state.background = $schemeObj.defaultBackground }

Write-ActiveThemeCss $state.scheme $state.buttonSkin ([bool]$state.energySword)
$themeCssPath = Join-Path $HubRoot 'css\active\theme.css'
$themeCssUri = ([Uri]$themeCssPath).AbsoluteUri

$bgCfg = Build-BackgroundConfig $schemeObj $state.background

# Write colors snippet for extension / debug
$snippet = @{
  scheme = $state.scheme
  background = $state.background
  buttonSkin = $state.buttonSkin
  energySword = [bool]$state.energySword
  colors = $schemeObj.colors
  tokenColors = $schemeObj.tokenColors
  backgroundConfig = $bgCfg
  themeCssUri = $themeCssUri
}
$snippet | ConvertTo-Json -Depth 30 | Set-Content (Join-Path $HubRoot 'css\active\colors.snippet.json') -Encoding UTF8

Save-State $state

if ($WriteSettings) {
  Merge-UserSettings $schemeObj $bgCfg $themeCssUri
}

Write-Host "Applied scheme=$($state.scheme) bg=$($state.background) button=$($state.buttonSkin) sword=$($state.energySword)"
Write-Host "theme.css => $themeCssUri"
